version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=somerootpass
      - MYSQL_PASSWORD=somepass
      - MYSQL_DATABASE=dockerizeme_db
      - MYSQL_USER=someuser
  web:
    build: .
    volumes:
      - ./:/var/www:delegated
    container_name: web
    ports:
      - 80:80